[package]
name = "atlas-local-lib"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

include = [
    "src/**",
    "Cargo.toml",
    "README.md",
    "CONTRIBUTING.md",
    "LICENSE",
    "license.html"
]

[dependencies]
bollard = "0.19.2"
thiserror = "2.0.16"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
